name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        type: environment
        required: true

run-name: Deploy ${{ inputs.environment }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_DISTRIBUTION: "zulu"
  JAVA_VERSION_FILE: ".java-version"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment != null && inputs.environment }}

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version-file: ${{ env.JAVA_VERSION_FILE }}

      - uses: gradle/actions/setup-gradle@v3

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ vars.IDENTITY_PROVIDER }}"
          service_account: "${{ vars.SERVICE_ACCOUNT }}"
          project_id: "${{ vars.GCP_PROJECT_ID }}"

      - name: Setup gcloud
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 419.0.0"

      - name: Check
        run: make check

      - name: "Deploy"
        run: |
          gcloud functions deploy template-kotlin-cloud-function \
          --gen2 \
          --entry-point=dev.goobar.CloudFunction \
          --runtime=java17 \
          --region=${{ vars.GCP_REGION }} \
          --trigger-http \
          --project=${{ vars.GCP_PROJECT_ID }} \
          --source=function/build/libs \
          --set-env-vars GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID }}



